### ISSUE TITLE
Some good todo resources

### ISSUE THREAD

**Issue by saibotsivad** [wamu885/todo#1]
Hey @lukehollis, Github told me you made this repo and I had only just found [this related resource](http://todomvc.com/), so I thought I'd pass it on. It's super handy.

**Comment by lukehollis** [comment]
@saibotsivad, great hearing from you!  I hope that you're doing well!  Thanks for the todo mvc resource.  This is our assignment repo for new potential developers that we would hire, so if you wanted to work with us, I bet you'd ace it!  Thanks again, and take care.
